spring.application.name=steel-trade-api
server.servlet.context-path=/api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/steel}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:steel}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:steel}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
